spring:
  datasource:
    url: jdbc:mysql://39.100.135.205:3306/db_test?useSSL=false&setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Qds3dp&
  redis:
    host: redis.data.ysujc.com
    password: Ym8s9tp
    port: 6379
    timeout: 60000


#用于心跳检测输出的日志
logging:
  level:
    root: INFO

